services:
  backend:
    image: erivas04/redbackend:latest
    container_name: red-backend
    restart: unless-stopped
    env_file:
      - ./backend.env
    networks:
      - proxy_network
      - db_network

  frontend:
    image: erivas04/redfrontend:latest
    container_name: red-frontend
    restart: unless-stopped
    networks:
      - proxy_network
    depends_on:
      - backend

networks:
  proxy_network:
    external: true
  db_network:
    external: true
    name: red_social_default
